from __future__ import annotations

from app.services.gcode_parser import extract_summary_comments, parse_gcode


SAMPLE = """\
; generated by orca
G90
M83
G1 Z0.2 F600
;LAYER_CHANGE
;Z:0.2
;TYPE:External perimeter
G1 X10 Y10 E0.1 F1200
G1 X20 Y10 E0.2
G1 X20 Y20 E0.3
;TYPE:Internal infill
G1 X15 Y15 F6000
G1 X18 Y18 E0.05
;LAYER_CHANGE
;Z:0.4
;TYPE:External perimeter
G1 X10 Y10 E0.05
G1 X20 Y10 E0.1
; estimated printing time (normal mode) = 1h 23m 45s
; filament used [mm] = 1234.5
; filament used [g] = 12.5
"""


def test_parse_basic_layers_and_features() -> None:
    parsed = parse_gcode(SAMPLE)
    assert parsed.layers, "expected at least one layer"
    assert parsed.layers[0].z == 0.2
    assert len(parsed.layers) >= 2

    legend = parsed.feature_legend
    assert "outer_wall" in legend
    assert "infill" in legend
    # The first layer should classify the perimeter extrudes as outer_wall
    first = parsed.layers[0]
    assert first.feature_ids
    assert legend["outer_wall"] in first.feature_ids


def test_extrude_vs_travel_buffers() -> None:
    parsed = parse_gcode(SAMPLE)
    first = parsed.layers[0]
    # extrudes are stored as 6 floats per segment; should be > 0
    assert len(first.extrude_segments) % 6 == 0
    assert len(first.travel_segments) % 6 == 0
    assert parsed.total_extruded > 0


def test_summary_comments() -> None:
    summary = extract_summary_comments(SAMPLE)
    assert "estimated printing time (normal mode)" in summary
    assert summary["filament used [mm]"] == "1234.5"


def test_bbox_includes_all_extrudes() -> None:
    parsed = parse_gcode(SAMPLE)
    minx, miny, _, maxx, maxy, _ = parsed.bbox
    assert minx <= 10 and maxx >= 20
    assert miny <= 10 and maxy >= 20
