services:
  minicloud:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "51820:51820/udp"
    environment:
      - MC_DATACENTER_CODE=dc
      - MC_IP_RANGE_START=10.100.0.10
      - MC_IP_RANGE_END=10.100.0.254
      - MC_IP_SUBNET_MASK=255.255.255.0
      - MC_IP_GATEWAY=10.100.0.1
      - MC_IP_DNS=8.8.8.8,8.8.4.4
      - MC_DB_PATH=/app/data/minicloud.db
      - MC_SSH_KEY_DIR=/app/data/ssh_keys
      - MC_WG_PRIVATE_KEY_PATH=/app/data/wg_private.key
      - MC_WG_PORT=51820
      - MC_WG_ADDRESS=10.200.0.1/24
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - minicloud_data:/app/data

volumes:
  minicloud_data:
